from __future__ import annotations

# VASUKI_V15_AUTONOMOUS_CODER

import base64
import io
import json
import posixpath
import re
import zipfile
from pathlib import PurePosixPath
from typing import Any

MAX_PROJECT_FILES = 60
MAX_FILE_CHARS = 140_000
MAX_TOTAL_CHARS = 2_200_000
MAX_ZIP_INPUT_BYTES = 10 * 1024 * 1024

SKIP_DIRS = {
    ".git", ".next", ".turbo", ".venv", "venv", "node_modules",
    "dist", "build", "coverage", "__pycache__",
}

BINARY_SUFFIXES = {
    ".7z", ".aab", ".apk", ".avi", ".bin", ".class", ".dll", ".dmg",
    ".doc", ".docx", ".exe", ".gif", ".gz", ".ico", ".jar", ".jpeg",
    ".jpg", ".mov", ".mp3", ".mp4", ".o", ".obj", ".pdf", ".png",
    ".pyc", ".so", ".tar", ".webp", ".woff", ".woff2", ".zip",
}

V15_PROJECT_SYSTEM_PROMPT = """
You are Vasuki V15 Autonomous Coder: a senior software architect, full-stack
engineer, debugger, DevOps engineer and product builder.

Create COMPLETE runnable multi-file software projects or modify existing
projects in any mainstream programming language/framework requested.

Rules:
- Return ONE valid JSON object only; no Markdown fence around the JSON.
- No TODOs, placeholders, omitted code, or "...rest of code".
- If the request is huge, create the smallest COMPLETE functional MVP that
  preserves the requested core features.
- Respect the requested stack; otherwise choose a sensible modern stack.
- Include all bootstrap/config files and README.md.
- Never include real secrets; use .env.example.
- Include Windows PowerShell commands for install, run, test/build.
- Commands must be project-local and non-destructive.
- Use secure defaults, validation, accessible responsive UI and clear errors.
- Do not claim code was executed/deployed/tested without evidence.
- For existing projects, return complete contents for changed/new files.

Required JSON:
{
  "project_name": "safe-project-name",
  "summary": "short explanation",
  "language": "primary language",
  "framework": "framework/runtime",
  "files": [{"path": "relative/path.ext", "content": "complete contents"}],
  "powershell": ["PowerShell command"],
  "run_commands": ["optional command"],
  "notes": ["important note"]
}

Keep the project under 60 files and reasonably compact.
""".strip()


def _safe_project_name(value: str) -> str:
    value = re.sub(r"[^A-Za-z0-9._-]+", "-", (value or "").strip())
    value = re.sub(r"-{2,}", "-", value).strip("-.")
    return (value or "vasuki-project")[:80]


def _safe_path(value: str) -> str:
    raw = (value or "").replace("\\\\", "/").strip().lstrip("/")
    raw = posixpath.normpath(raw)
    if not raw or raw in {".", ".."} or raw.startswith("../"):
        raise ValueError("Unsafe or empty project path.")
    path = PurePosixPath(raw)
    if any(part in {"", ".", ".."} for part in path.parts):
        raise ValueError("Unsafe project path.")
    if any(part.casefold() in SKIP_DIRS for part in path.parts):
        raise ValueError("Dependency/build cache folders are not allowed.")
    return str(path)


def _json_from_text(text: str) -> dict[str, Any]:
    cleaned = (text or "").strip()
    cleaned = re.sub(r"^```(?:json)?\\s*", "", cleaned, flags=re.I)
    cleaned = re.sub(r"\\s*```$", "", cleaned)
    candidates = [cleaned]
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start >= 0 and end > start:
        candidates.append(cleaned[start:end + 1])
    last_error: Exception | None = None
    for candidate in candidates:
        try:
            value = json.loads(candidate)
            if isinstance(value, dict):
                return value
        except Exception as exc:
            last_error = exc
    raise ValueError(f"AI project response was not valid JSON: {last_error}")


def _generated_readme(
    project_name: str,
    summary: str,
    language: str,
    framework: str,
    powershell: list[str],
    notes: list[str],
) -> str:
    commands = "\\n".join(f"    {command}" for command in powershell)
    if not commands:
        commands = "    # See project files for run instructions"
    note_lines = "\\n".join(f"- {note}" for note in notes)
    if not note_lines:
        note_lines = "- Generated by Vasuki AI V15."
    return (
        f"# {project_name}\\n\\n{summary}\\n\\n"
        f"## Stack\\n\\n- Language: {language}\\n"
        f"- Framework/runtime: {framework}\\n\\n"
        f"## Windows PowerShell\\n\\n{commands}\\n\\n"
        f"## Notes\\n\\n{note_lines}\\n"
    )


def normalize_project_payload(
    payload: dict[str, Any],
    *,
    fallback_name: str = "vasuki-project",
) -> dict[str, Any]:
    project_name = _safe_project_name(
        str(payload.get("project_name") or fallback_name)
    )
    summary = str(
        payload.get("summary") or "Vasuki AI generated project."
    ).strip()
    language = str(payload.get("language") or "mixed").strip()[:80]
    framework = str(payload.get("framework") or "custom").strip()[:120]

    raw_files = payload.get("files")
    if not isinstance(raw_files, list) or not raw_files:
        raise ValueError("AI project response did not contain project files.")

    files: list[dict[str, str]] = []
    seen: set[str] = set()
    total_chars = 0

    for item in raw_files:
        if not isinstance(item, dict):
            continue
        try:
            path = _safe_path(str(item.get("path") or ""))
        except ValueError:
            continue
        content = item.get("content")
        if not isinstance(content, str):
            continue
        if len(content) > MAX_FILE_CHARS:
            content = content[:MAX_FILE_CHARS]
        key = path.casefold()
        if key in seen:
            continue
        if len(files) >= MAX_PROJECT_FILES:
            break
        if total_chars + len(content) > MAX_TOTAL_CHARS:
            break
        seen.add(key)
        total_chars += len(content)
        files.append({"path": path, "content": content})

    if not files:
        raise ValueError("No safe text source files were returned by the AI.")

    powershell = [
        str(value).strip()
        for value in (payload.get("powershell") or [])
        if isinstance(value, str) and value.strip()
    ][:16]
    run_commands = [
        str(value).strip()
        for value in (payload.get("run_commands") or [])
        if isinstance(value, str) and value.strip()
    ][:16]
    notes = [
        str(value).strip()
        for value in (payload.get("notes") or [])
        if isinstance(value, str) and value.strip()
    ][:20]

    if not any(item["path"].casefold() == "readme.md" for item in files):
        files.append({
            "path": "README.md",
            "content": _generated_readme(
                project_name, summary, language, framework, powershell, notes
            ),
        })

    return {
        "project_name": project_name,
        "summary": summary[:2000],
        "language": language,
        "framework": framework,
        "files": files,
        "powershell": powershell,
        "run_commands": run_commands,
        "notes": notes,
    }


def parse_project_response(
    text: str,
    *,
    fallback_name: str = "vasuki-project",
) -> dict[str, Any]:
    return normalize_project_payload(
        _json_from_text(text),
        fallback_name=fallback_name,
    )


def build_project_prompt(
    user_request: str,
    *,
    planner_context: dict[str, Any] | None = None,
    existing_files: list[dict[str, str]] | None = None,
) -> str:
    parts = ["USER REQUEST:", user_request.strip()]
    if planner_context:
        parts.extend([
            "",
            "VASUKI AUTONOMY PLAN (guidance only):",
            json.dumps(planner_context, ensure_ascii=False)[:12000],
        ])
    if existing_files:
        parts.extend([
            "",
            "EXISTING PROJECT FILES:",
            "Return complete contents for changed/new files. "
            "Unchanged files are merged back automatically.",
        ])
        for item in existing_files:
            parts.append(
                f"\\n--- FILE: {item['path']} ---\\n{item['content']}"
            )
    parts.extend([
        "",
        "Build the project now. Follow the required JSON schema exactly.",
    ])
    return "\\n".join(parts)


def extract_zip_text_files(data: bytes) -> list[dict[str, str]]:
    if len(data) > MAX_ZIP_INPUT_BYTES:
        raise ValueError("ZIP project is larger than 10 MB.")
    files: list[dict[str, str]] = []
    total_chars = 0
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        infos = sorted(
            archive.infolist(),
            key=lambda info: info.filename.casefold(),
        )
        for info in infos:
            if info.is_dir():
                continue
            try:
                path = _safe_path(info.filename)
            except ValueError:
                continue
            suffix = PurePosixPath(path).suffix.casefold()
            if suffix in BINARY_SUFFIXES or info.file_size > 300_000:
                continue
            raw = archive.read(info)
            if b"\\x00" in raw[:4096]:
                continue
            try:
                text = raw.decode("utf-8")
            except UnicodeDecodeError:
                continue
            if total_chars + len(text) > MAX_TOTAL_CHARS:
                break
            total_chars += len(text)
            files.append({"path": path, "content": text})
            if len(files) >= MAX_PROJECT_FILES:
                break
    if not files:
        raise ValueError("No supported text source files were found in the ZIP.")
    return files


def merge_existing_files(
    existing_files: list[dict[str, str]],
    generated_project: dict[str, Any],
) -> dict[str, Any]:
    merged: dict[str, tuple[str, str]] = {}
    for item in existing_files:
        path = _safe_path(item["path"])
        merged[path.casefold()] = (path, item["content"])
    for item in generated_project["files"]:
        path = _safe_path(item["path"])
        merged[path.casefold()] = (path, item["content"])
    result = dict(generated_project)
    result["files"] = [
        {"path": path, "content": content}
        for _, (path, content) in sorted(merged.items())
    ][:MAX_PROJECT_FILES]
    return normalize_project_payload(
        result,
        fallback_name=str(
            generated_project.get("project_name") or "vasuki-project"
        ),
    )


def _language_for_path(path: str) -> str:
    suffix = PurePosixPath(path).suffix.casefold()
    return {
        ".c": "c", ".cpp": "cpp", ".cs": "csharp", ".css": "css",
        ".dart": "dart", ".go": "go", ".html": "html", ".java": "java",
        ".js": "javascript", ".jsx": "jsx", ".kt": "kotlin", ".php": "php",
        ".py": "python", ".rb": "ruby", ".rs": "rust", ".sql": "sql",
        ".swift": "swift", ".ts": "typescript", ".tsx": "tsx", ".vue": "vue",
    }.get(suffix, suffix.lstrip(".") or "text")


def _primary_file(project: dict[str, Any]) -> dict[str, str]:
    preferred = [
        "index.html", "src/app/page.tsx", "app/page.tsx", "src/App.tsx",
        "src/App.jsx", "src/main.tsx", "src/main.jsx", "main.py", "app.py",
        "server.py", "Program.cs", "Main.java", "main.go", "src/main.rs",
    ]
    by_key = {
        item["path"].casefold(): item
        for item in project["files"]
    }
    for candidate in preferred:
        if candidate.casefold() in by_key:
            return by_key[candidate.casefold()]
    return project["files"][0]


def _preview_doc(project: dict[str, Any]) -> str:
    by_name = {
        PurePosixPath(item["path"]).name.casefold(): item["content"]
        for item in project["files"]
    }
    html = by_name.get("index.html", "")
    if not html:
        return ""
    css = by_name.get("style.css", "") or by_name.get("styles.css", "")
    js = by_name.get("script.js", "") or by_name.get("main.js", "")
    doc = html
    if css:
        style = f"<style>\\n{css}\\n</style>"
        if re.search(r"</head>", doc, flags=re.I):
            doc = re.sub(
                r"</head>", style + "\\n</head>", doc,
                count=1, flags=re.I,
            )
        else:
            doc = style + doc
    if js:
        safe_js = re.sub(r"</script", r"<\\/script", js, flags=re.I)
        script = f"<script>\\n{safe_js}\\n</script>"
        if re.search(r"</body>", doc, flags=re.I):
            doc = re.sub(
                r"</body>", script + "\\n</body>", doc,
                count=1, flags=re.I,
            )
        else:
            doc += script
    return doc[:400000]


def _artifact(name: str, mime_type: str, data: bytes) -> dict[str, Any]:
    encoded = base64.b64encode(data).decode("ascii")
    return {
        "name": name,
        "mime_type": mime_type,
        "size_bytes": len(data),
        "data_url": f"data:{mime_type};base64,{encoded}",
    }


def _zip_bytes(project: dict[str, Any]) -> bytes:
    stream = io.BytesIO()
    with zipfile.ZipFile(
        stream, "w", compression=zipfile.ZIP_DEFLATED
    ) as archive:
        for item in project["files"]:
            archive.writestr(
                item["path"],
                item["content"].encode("utf-8"),
            )
        if project.get("powershell"):
            ps1 = (
                "$ErrorActionPreference = 'Stop'\\n"
                + "\\n".join(project["powershell"])
                + "\\n"
            )
            archive.writestr("VASUKI_RUN.ps1", ps1.encode("utf-8"))
        archive.writestr(
            "VASUKI_PROJECT.json",
            json.dumps({
                "project_name": project["project_name"],
                "summary": project["summary"],
                "language": project["language"],
                "framework": project["framework"],
                "powershell": project["powershell"],
                "run_commands": project["run_commands"],
                "notes": project["notes"],
                "files": [item["path"] for item in project["files"]],
            }, ensure_ascii=False, indent=2).encode("utf-8"),
        )
    return stream.getvalue()


def package_project_response(
    project: dict[str, Any],
    *,
    provider: str,
) -> dict[str, Any]:
    project = normalize_project_payload(
        project,
        fallback_name=str(
            project.get("project_name") or "vasuki-project"
        ),
    )
    zip_name = f"{project['project_name']}.zip"
    artifacts = [
        _artifact(zip_name, "application/zip", _zip_bytes(project))
    ]
    readme = next(
        (
            item for item in project["files"]
            if item["path"].casefold() == "readme.md"
        ),
        None,
    )
    if readme and len(readme["content"]) <= 120000:
        artifacts.append(
            _artifact(
                "README.md",
                "text/markdown",
                readme["content"].encode("utf-8"),
            )
        )

    primary = _primary_file(project)
    powershell = [
        f"Expand-Archive .\\\\{zip_name} "
        f"-DestinationPath .\\\\{project['project_name']}",
        f"Set-Location .\\\\{project['project_name']}",
        *project["powershell"],
    ]
    command_lines = "\\n".join(
        f"{index + 1}. `{command}`"
        for index, command in enumerate(powershell)
    )
    answer = (
        f"Project ready: **{project['project_name']}**\\n\\n"
        f"{project['summary']}\\n\\n"
        f"Stack: **{project['language']} / {project['framework']}** · "
        f"{len(project['files'])} source files.\\n\\n"
        f"Windows PowerShell:\\n{command_lines}\\n\\n"
        "The complete ZIP is attached below. Upload that ZIP back to "
        "Vasuki AI whenever you want changes."
    )

    return {
        "ok": True,
        "version": "v15",
        "answer": answer,
        "provider": provider,
        "project_name": project["project_name"],
        "summary": project["summary"],
        "language": project["language"],
        "framework": project["framework"],
        "tree": "\\n".join(
            item["path"] for item in project["files"]
        ),
        "powershell": powershell,
        "primary_file": primary["path"],
        "primary_language": _language_for_path(primary["path"]),
        "primary_code": primary["content"],
        "preview_doc": _preview_doc(project),
        "files": artifacts,
        "warnings": [],
        "processed_files": [
            item["path"] for item in project["files"]
        ],
    }


def coder_health() -> dict[str, Any]:
    return {
        "version": "v15",
        "features": [
            "autonomous-project-builder",
            "multi-file-zip-artifacts",
            "windows-powershell-runbook",
            "existing-zip-project-modifier",
            "language-agnostic-code-packaging",
            "puter-emergency-coding-fallback",
            "project-preview-bridge",
            "safe-path-and-secret-contract",
        ],
        "db_migration_required": False,
        "new_api_key_required": False,
        "max_project_files": MAX_PROJECT_FILES,
        "max_zip_input_mb": MAX_ZIP_INPUT_BYTES // (1024 * 1024),
    }
