"use client";
import { useEffect, useMemo, useState } from "react";
import { createBackupV9, fetchSecurityCenterV9, recordSecretRotationV9, resolveErrorV9, restoreBackupV9, type SecurityCenterV9 } from "@/lib/api";
import { supabase } from "@/lib/supabase";
async function accessToken(){ const {data}=await supabase.auth.getSession(); const token=data.session?.access_token; if(!token) throw new Error("Please sign in again."); return token; }
function dateText(value:unknown){ if(!value) return "-"; const date=new Date(String(value)); return Number.isNaN(date.getTime())?String(value):date.toLocaleString(); }
export default function SecurityPage(){
 const [data,setData]=useState<SecurityCenterV9|null>(null),[busy,setBusy]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[rotationName,setRotationName]=useState(""),[previousFingerprint,setPreviousFingerprint]=useState("");
 async function load(){ setError(""); try{ const token=await accessToken(); setData(await fetchSecurityCenterV9(token)); }catch(err){ setError(err instanceof Error?err.message:"Security Center could not be loaded."); } }
 useEffect(()=>{void load();},[]);
 const latestEval=useMemo(()=>data?.evals?.[0] as Record<string,unknown>|undefined,[data?.evals]); const release=(data?.release_health||{}) as Record<string,unknown>;
 async function createBackup(){setBusy("backup");setError("");setMessage("");try{const token=await accessToken();await createBackupV9(token,"Owner Security Center backup");setMessage("Application-level logical backup created.");await load();}catch(err){setError(err instanceof Error?err.message:"Backup failed.");}finally{setBusy("");}}
 async function dryRunRestore(id:string){setBusy(`restore-${id}`);setError("");try{const token=await accessToken();const result=await restoreBackupV9(token,id,false,"");window.alert(`Dry run complete.\n${JSON.stringify(result,null,2)}`);}catch(err){setError(err instanceof Error?err.message:"Restore dry run failed.");}finally{setBusy("");}}
 async function applyRestore(id:string){const phrase=window.prompt("Dangerous operation. Type exactly: RESTORE VASUKI BACKUP");if(phrase!=="RESTORE VASUKI BACKUP")return;if(!window.confirm("Apply this logical backup now? Restore is best-effort and not atomic."))return;setBusy(`restore-${id}`);setError("");try{const token=await accessToken();const result=await restoreBackupV9(token,id,true,phrase);setMessage(`Restore finished: ${JSON.stringify(result)}`);await load();}catch(err){setError(err instanceof Error?err.message:"Restore failed.");}finally{setBusy("");}}
 async function markResolved(id:number){setBusy(`error-${id}`);try{const token=await accessToken();await resolveErrorV9(token,id);await load();}catch(err){setError(err instanceof Error?err.message:"Error could not be resolved.");}finally{setBusy("");}}
 async function recordRotation(){if(!rotationName||!previousFingerprint)return;setBusy("rotation");setError("");try{const token=await accessToken();await recordSecretRotationV9(token,rotationName,previousFingerprint,"Recorded from Security Center");setMessage("Secret rotation fingerprint verified and recorded.");setPreviousFingerprint("");await load();}catch(err){setError(err instanceof Error?err.message:"Rotation could not be recorded.");}finally{setBusy("");}}
 return <main className="pv-v9-security-page"><header className="pv-v9-security-head"><div><p className="pv-v8-kicker">V9 Phase 6</p><h1>Security & Reliability Center</h1><p>Owner-only audit, errors, secret rotation, logical backups, release health and Vasuki Eval Score.</p></div><nav><a href="/">Chat</a><a href="/owner">Owner</a><a href="/operations">Operations</a></nav></header>{error?<div className="pv-v8-error pv-v9-security-alert" role="alert">{error}</div>:null}{message?<div className="pv-v9-security-success" role="status">{message}</div>:null}
 <section className="pv-v9-security-summary"><article><span>Security score</span><strong>{data?.security?.score??"-"}<small>/100</small></strong><em>Grade {data?.security?.grade||"-"}</em></article><article><span>Unresolved errors</span><strong>{data?.errors?.unresolved??"-"}</strong><em>{data?.errors?.total??0} in 7 days</em></article><article><span>Release health</span><strong className="pv-v9-security-word">{String(release.status||"-")}</strong><em>production checks</em></article><article><span>Vasuki Eval Score</span><strong>{latestEval?.overall_score!=null?String(latestEval.overall_score):"-"}<small>/100</small></strong><em>{latestEval?dateText(latestEval.created_at):"Run eval suite"}</em></article></section>
 <section className="pv-v9-security-grid"><article className="pv-v9-security-card"><div className="pv-v9-security-card-head"><div><p className="pv-v8-kicker">43</p><h2>Security Audit V2</h2></div><button onClick={()=>void load()}>Refresh</button></div><div className="pv-v9-security-list">{(data?.security?.findings||[]).length?(data?.security?.findings||[]).map((item,index)=><div key={`${item.check}-${index}`}><b>{item.severity}</b><span><strong>{item.check}</strong><small>{item.detail}</small></span></div>):<p>No current audit findings.</p>}</div></article>
 <article className="pv-v9-security-card"><p className="pv-v8-kicker">45</p><h2>Secret Rotation</h2><p className="pv-v9-security-muted">Values are never shown. Rotate in Render/provider dashboard, redeploy, then record the change using the old fingerprint.</p><label><span>Secret</span><select value={rotationName} onChange={e=>setRotationName(e.target.value)}><option value="">Select configured secret</option>{(data?.security?.secret_inventory||[]).filter(row=>row.configured).map(row=><option key={row.name} value={row.name}>{row.name} · current {row.fingerprint}</option>)}</select></label><label><span>Previous fingerprint</span><input value={previousFingerprint} onChange={e=>setPreviousFingerprint(e.target.value)} placeholder="old 16-char fingerprint" /></label><button disabled={!rotationName||!previousFingerprint||busy==="rotation"} onClick={()=>void recordRotation()}>{busy==="rotation"?"Verifying...":"Verify & record rotation"}</button></article>
 <article className="pv-v9-security-card pv-v9-security-wide"><div className="pv-v9-security-card-head"><div><p className="pv-v8-kicker">46</p><h2>Backup / Restore</h2></div><button disabled={busy==="backup"} onClick={()=>void createBackup()}>{busy==="backup"?"Creating...":"Create logical backup"}</button></div><p className="pv-v9-security-muted">Protects core application rows. It does not replace Supabase native disaster-recovery backups and does not include Auth identities or storage object bytes.</p><div className="pv-v9-security-table-wrap"><table><thead><tr><th>Created</th><th>Size</th><th>Tables</th><th>Actions</th></tr></thead><tbody>{(data?.backups||[]).map(raw=>{const row=raw as Record<string,unknown>;const id=String(row.id||"");const count=Object.values((row.table_counts||{}) as Record<string,number>).reduce((a,b)=>a+Number(b||0),0);return <tr key={id}><td>{dateText(row.created_at)}</td><td>{Math.round(Number(row.compressed_bytes||0)/1024)} KB</td><td>{count} rows</td><td><button onClick={()=>void dryRunRestore(id)}>Dry run</button><button className="pv-v9-danger-button" onClick={()=>void applyRestore(id)}>Restore</button></td></tr>;})}</tbody></table></div></article>
 <article className="pv-v9-security-card pv-v9-security-wide"><p className="pv-v8-kicker">47</p><h2>Error Tracking</h2><div className="pv-v9-security-table-wrap"><table><thead><tr><th>Time</th><th>Type</th><th>Message</th><th>Status</th></tr></thead><tbody>{(data?.errors?.recent||[]).slice(0,30).map(raw=>{const row=raw as Record<string,unknown>;const id=Number(row.id||0);const resolved=Boolean(row.resolved_at);return <tr key={id}><td>{dateText(row.created_at)}</td><td>{String(row.event_type||"-")}</td><td className="pv-v9-security-message">{String(row.error_message||"-")}</td><td>{resolved?"Resolved":<button disabled={busy===`error-${id}`} onClick={()=>void markResolved(id)}>Resolve</button>}</td></tr>;})}</tbody></table></div></article>
 <article className="pv-v9-security-card pv-v9-security-wide"><p className="pv-v8-kicker">44</p><h2>Audit Logs</h2><div className="pv-v9-security-table-wrap"><table><thead><tr><th>Time</th><th>Action</th><th>Outcome</th><th>Request</th></tr></thead><tbody>{(data?.audit_logs||[]).slice(0,40).map(raw=>{const row=raw as Record<string,unknown>;return <tr key={String(row.id)}><td>{dateText(row.created_at)}</td><td>{String(row.action||"-")}</td><td>{String(row.outcome||"-")}</td><td>{String(row.request_id||"-").slice(0,16)}</td></tr>;})}</tbody></table></div></article></section></main>;
}
