-- Vasuki AI production v2
-- Run this complete file once in Supabase Dashboard > SQL Editor.

create table if not exists public.user_daily_usage (
  user_id uuid not null references auth.users(id) on delete cascade,
  usage_date date not null,
  message_count integer not null default 0 check (message_count >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, usage_date)
);

alter table public.user_daily_usage enable row level security;

create or replace function public.consume_chat_quota(
  p_user_id uuid,
  p_daily_limit integer
)
returns table (
  allowed boolean,
  message_count integer,
  daily_remaining integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_usage_date date := (now() at time zone 'Asia/Kolkata')::date;
  v_count integer;
begin
  if p_user_id is null or p_daily_limit < 1 then
    raise exception 'Invalid quota arguments';
  end if;

  insert into public.user_daily_usage (
    user_id,
    usage_date,
    message_count,
    updated_at
  )
  values (
    p_user_id,
    v_usage_date,
    0,
    now()
  )
  on conflict (user_id, usage_date) do nothing;

  select u.message_count
  into v_count
  from public.user_daily_usage u
  where u.user_id = p_user_id
    and u.usage_date = v_usage_date
  for update;

  if v_count >= p_daily_limit then
    return query select false, v_count, 0;
    return;
  end if;

  v_count := v_count + 1;

  update public.user_daily_usage
  set message_count = v_count,
      updated_at = now()
  where user_id = p_user_id
    and usage_date = v_usage_date;

  return query
  select true, v_count, greatest(0, p_daily_limit - v_count);
end;
$$;

revoke all on function public.consume_chat_quota(uuid, integer)
from public, anon, authenticated;
grant execute on function public.consume_chat_quota(uuid, integer)
to service_role;


create table if not exists public.user_chat_messages (
  id uuid primary key default gen_random_uuid(),
  chat_id uuid not null references public.user_chats(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text not null,
  position integer not null check (position >= 0),
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  image_url text,
  file_name text,
  provider text,
  sources jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (chat_id, client_id)
);

create index if not exists user_chat_messages_chat_position_idx
on public.user_chat_messages (chat_id, position);

create index if not exists user_chat_messages_user_updated_idx
on public.user_chat_messages (user_id, updated_at desc);

alter table public.user_chat_messages enable row level security;

drop policy if exists "Users read own chat messages"
on public.user_chat_messages;
create policy "Users read own chat messages"
on public.user_chat_messages
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users insert own chat messages"
on public.user_chat_messages;
create policy "Users insert own chat messages"
on public.user_chat_messages
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users update own chat messages"
on public.user_chat_messages;
create policy "Users update own chat messages"
on public.user_chat_messages
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users delete own chat messages"
on public.user_chat_messages;
create policy "Users delete own chat messages"
on public.user_chat_messages
for delete
to authenticated
using (auth.uid() = user_id);


create table if not exists public.system_error_events (
  id bigint generated by default as identity primary key,
  request_id text not null,
  event_type text not null,
  provider text,
  error_message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists system_error_events_created_idx
on public.system_error_events (created_at desc);

alter table public.system_error_events enable row level security;

-- No client policies are created for system_error_events. Only backend
-- service credentials can write/read this operational log.
