-- Vasuki AI V11 persistent tables.
create extension if not exists pgcrypto;
do $$
begin
  execute 'create extension if not exists pg_stat_statements';
exception when others then
  raise notice 'pg_stat_statements could not be enabled automatically: %', SQLERRM;
end $$;

create table if not exists public.v11_eval_runs (
  id uuid primary key,
  release text not null,
  mode text not null,
  case_count integer not null default 0,
  score numeric not null default 0,
  category_scores jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.v11_memory_facts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  project_id uuid null,
  key text not null,
  key_norm text not null,
  value text not null,
  source text not null default 'user',
  status text not null default 'active' check (status in ('active','superseded','deprecated')),
  valid_from timestamptz not null default now(),
  valid_to timestamptz null,
  supersedes uuid null references public.v11_memory_facts(id) on delete set null,
  updated_at timestamptz not null default now()
);
create index if not exists v11_memory_user_key_idx on public.v11_memory_facts(user_id,key_norm,status,updated_at desc);

create table if not exists public.v11_research_kb (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  project_id uuid null,
  title text not null,
  query text not null,
  answer text not null,
  sources jsonb not null default '[]'::jsonb,
  verification jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists v11_research_kb_user_idx on public.v11_research_kb(user_id,project_id,created_at desc);

create table if not exists public.v11_tool_permissions (
  id uuid primary key,
  user_id uuid not null,
  action text not null,
  fingerprint text not null,
  expires_at_epoch bigint not null,
  used boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists v11_tool_perm_user_idx on public.v11_tool_permissions(user_id,used,expires_at_epoch);

create table if not exists public.v11_scheduled_tasks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  title text not null,
  prompt text not null,
  run_at timestamptz null,
  cron text null,
  status text not null default 'scheduled',
  last_run_at timestamptz null,
  result jsonb null,
  created_at timestamptz not null default now()
);
create index if not exists v11_tasks_due_idx on public.v11_scheduled_tasks(status,run_at);

create table if not exists public.v11_provider_quality (
  id uuid primary key default gen_random_uuid(),
  task_type text not null,
  provider text not null,
  signal_type text not null,
  signal_value numeric not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists v11_provider_quality_idx on public.v11_provider_quality(task_type,provider,created_at desc);

create table if not exists public.v11_reliability_samples (
  id bigint generated by default as identity primary key,
  route text not null,
  status integer not null,
  latency_ms numeric not null,
  first_token_ms numeric null,
  provider text null,
  fallback boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists v11_reliability_created_idx on public.v11_reliability_samples(created_at desc);

create table if not exists public.v11_project_graph_nodes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  project_id uuid not null,
  node_key text not null,
  kind text not null,
  name text not null,
  path text not null,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique(project_id,node_key)
);

create table if not exists public.v11_project_graph_edges (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  project_id uuid not null,
  from_key text not null,
  to_key text not null,
  edge_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.v11_abuse_events (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  subject_hash text not null,
  event_type text not null,
  score numeric not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.v11_retention_policies (
  id uuid primary key default gen_random_uuid(),
  user_id uuid null,
  scope text not null,
  retention_days integer not null check (retention_days >= 0),
  updated_at timestamptz not null default now(),
  unique(user_id,scope)
);

alter table public.v11_memory_facts enable row level security;
alter table public.v11_research_kb enable row level security;
alter table public.v11_tool_permissions enable row level security;
alter table public.v11_scheduled_tasks enable row level security;
alter table public.v11_project_graph_nodes enable row level security;
alter table public.v11_project_graph_edges enable row level security;
alter table public.v11_retention_policies enable row level security;

drop policy if exists v11_memory_self on public.v11_memory_facts;
create policy v11_memory_self on public.v11_memory_facts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists v11_research_self on public.v11_research_kb;
create policy v11_research_self on public.v11_research_kb for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists v11_perm_self on public.v11_tool_permissions;
create policy v11_perm_self on public.v11_tool_permissions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists v11_task_self on public.v11_scheduled_tasks;
create policy v11_task_self on public.v11_scheduled_tasks for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists v11_graph_nodes_self on public.v11_project_graph_nodes;
create policy v11_graph_nodes_self on public.v11_project_graph_nodes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists v11_graph_edges_self on public.v11_project_graph_edges;
create policy v11_graph_edges_self on public.v11_project_graph_edges for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists v11_retention_self on public.v11_retention_policies;
create policy v11_retention_self on public.v11_retention_policies for all using (user_id is null or auth.uid() = user_id) with check (user_id is null or auth.uid() = user_id);

create or replace function public.v11_db_performance()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  select jsonb_build_object(
    'database_size_bytes', pg_database_size(current_database()),
    'tables', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'table', relname,
        'seq_scan', seq_scan,
        'idx_scan', idx_scan,
        'n_live_tup', n_live_tup,
        'n_dead_tup', n_dead_tup
      ) order by n_live_tup desc), '[]'::jsonb)
      from pg_stat_user_tables
    ),
    'slow_queries', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'query', left(query,500),
        'calls', calls,
        'mean_exec_time_ms', round(mean_exec_time::numeric,2),
        'total_exec_time_ms', round(total_exec_time::numeric,2)
      ) order by mean_exec_time desc), '[]'::jsonb)
      from (select query,calls,mean_exec_time,total_exec_time from pg_stat_statements order by mean_exec_time desc limit 20) q
    )
  ) into result;
  return result;
exception when others then
  return jsonb_build_object('available',false,'error',SQLERRM);
end;
$$;

revoke all on function public.v11_db_performance() from public;
grant execute on function public.v11_db_performance() to authenticated, service_role;
